chore: bump stack versions
elastic/apm-pipeline-library pull request #1455
Opened 2021-12-15 17:26 UTC by kuisathaverat

## What does this PR do?

Update the elastic stack versions

2021-12-15 17:35 UTC, apmmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-shared%2Fapm-pipeline-library-mbp%2FPR-1455/detail/PR-1455/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-shared%2Fapm-pipeline-library-mbp%2FPR-1455/detail/PR-1455/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-shared%2Fapm-pipeline-library-mbp%2FPR-1455/detail/PR-1455/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-shared%2Fapm-pipeline-library-mbp%2FPR-1455/detail/PR-1455/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://apm-pipeline-library_1455.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/apm-ci/transactions/view?rangeFrom=2021-12-15T17:16:38.746Z&rangeTo=2021-12-15T17:36:38.746Z&transactionName=apm-shared%2Fapm-pipeline-library-mbp%2FPR-%7Bnumber%7D&transactionType=unknown&latencyAggregationType=avg&traceId=b36670aba48ed32b5cb9e9dc8a1d6681&transactionId=7a45e5a53aff26a5)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2021-12-15T17:26:38.746+0000


* Duration: 9 min 34 sec


* Commit: 5bf3c023c4c73526e0feb81cd661fbe2235f0157



#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 1315  |
| Skipped      | 2 |
| Total        | 1317   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->












## :green_heart: Flaky test report
Tests succeeded.



## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.


- `run infra tests` : Run the test-infra test.


- `run` `elasticsearch-ci/docs` : Re-trigger the docs validation. (use unformatted text in the comment!)




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2021-12-15 17:41 UTC, cachedout approved these changes

2021-12-15 18:32 UTC, v1v requested changes
Good catch! I just updated the source of truth pipeline in charge of doing this in https://github.com/elastic/apm-pipeline-library/pull/1457.

I'd say to close this PR and wait for tomorrow's run and see it did the magic

We might need to automate how it's upgraded, we were told to use GitHub releases query to know the latest release for each major as the source of truth.

2021-12-16 09:44 UTC, kuisathaverat commented
superseded by https://github.com/elastic/apm-pipeline-library/pull/1461

2021-12-16 09:44 UTC, closed without merging