feat: job to anage the edge-litle cluster
elastic/apm-pipeline-library pull request #1755
Opened 2022-06-29 16:15 UTC by kuisathaverat

## What does this PR do?

## Why is it important?

## Related issues
Closes #ISSUE

2022-06-29 16:25 UTC, apmmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-shared%2Fapm-pipeline-library-mbp%2FPR-1755/detail/PR-1755/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-shared%2Fapm-pipeline-library-mbp%2FPR-1755/detail/PR-1755/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-shared%2Fapm-pipeline-library-mbp%2FPR-1755/detail/PR-1755/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-shared%2Fapm-pipeline-library-mbp%2FPR-1755/detail/PR-1755/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://apm-pipeline-library_1755.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/apm-ci/transactions/view?rangeFrom=2022-06-29T16:06:06.782Z&rangeTo=2022-06-29T16:26:06.782Z&transactionName=BUILD+apm-shared%2Fapm-pipeline-library-mbp%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=822e46afcf7f06f5e322693219bd7579&transactionId=06d1beccfad8a773)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-06-29T16:16:06.782+0000


* Duration: 9 min 24 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 1500  |
| Skipped      | 2 |
| Total        | 1502   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














## :green_heart: Flaky test report
Tests succeeded.



## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.


- `run infra tests` : Run the test-infra test.


- `/test all` : Re-trigger the build for all the stages.


- `run` `elasticsearch-ci/docs` : Re-trigger the docs validation. (use unformatted text in the comment!)




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-06-29 17:10 UTC, v1v requested changes
`little` or `lite`?

2022-06-29 18:12 UTC, kuisathaverat commented on .ci/jobDSL/jobs/apm-ci/apm-shared/oblt-test-env/edge-litle.groovy
> +  description("Job to create a edge-litle- oblt cluster every day.")
```suggestion
pipelineJob("apm-shared/oblt-test-env/edge-lite-oblt-cluster") {
  displayName("edge-litle-oblt cluster")
  description("Job to create a edge-lite- oblt cluster every day.")
```
```suggestion
pipelineJob("apm-shared/oblt-test-env/edge-litle-oblt-cluster") {
  displayName("edge-litle-oblt cluster")
  description("Job to create a edge-litle- oblt cluster every day.")
```

2022-06-29 18:12 UTC, kuisathaverat commented on .ci/jobDSL/jobs/apm-ci/apm-shared/oblt-test-env/edge-litle.groovy
> +      scriptPath(".ci/edge-litle.groovy")
```suggestion
      scriptPath(".ci/edge-lite.groovy")
```

2022-06-29 18:13 UTC, kuisathaverat commented on .ci/jobDSL/jobs/apm-ci/apm-shared/oblt-test-env/edge-litle.groovy
> +  description("Job to create a edge-lite- oblt cluster every day.")
```suggestion
pipelineJob("apm-shared/oblt-test-env/edge-lite-oblt-cluster") {
  displayName("edge-lite-oblt cluster")
  description("Job to create a edge-lite- oblt cluster every day.")
```

2022-06-29 18:13 UTC, kuisathaverat commented on .ci/jobDSL/jobs/apm-ci/apm-shared/oblt-test-env/edge-litle.groovy
> +  description("Job to create a edge-lite- oblt cluster every day.")
```suggestion
  description("Job to create a edge-lite-oblt cluster every day.")
```

2022-06-30 08:32 UTC, v1v approved these changes
LGTM.

I just renamed one of the files that was still pointing to `litle`

2022-07-05 10:28 UTC, merged