dependabot: less often
elastic/apm-pipeline-library pull request #1863
Opened 2022-08-31 12:17 UTC by v1v

## What does this PR do?

Run less often the dependabot bumps

## Why is it important?

There is no need to be up-to-date immediately, so we can reduce the code review overhead/notifications a bit

2022-08-31 12:18 UTC, apmmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-shared%2Fapm-pipeline-library-mbp%2FPR-1863/detail/PR-1863/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-shared%2Fapm-pipeline-library-mbp%2FPR-1863/detail/PR-1863/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-shared%2Fapm-pipeline-library-mbp%2FPR-1863/detail/PR-1863/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-shared%2Fapm-pipeline-library-mbp%2FPR-1863/detail/PR-1863/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://apm-pipeline-library_1863.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/apm-ci/transactions/view?rangeFrom=2022-08-31T12:07:30.315Z&rangeTo=2022-08-31T12:27:30.315Z&transactionName=BUILD+apm-shared%2Fapm-pipeline-library-mbp%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=02203c0873567eed8bd1ac5bd9cf3c21&transactionId=71446d8b86c12290)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-08-31T12:17:30.315+0000


* Duration: 1 min 55 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














## :grey_exclamation: Flaky test report
No test was executed to be analysed.



## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.


- `run infra tests` : Run the test-infra test.


- `/test all` : Re-trigger the build for all the stages.


- `run` `elasticsearch-ci/docs` : Re-trigger the docs validation. (use unformatted text in the comment!)




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-09-05 10:02 UTC, amannocci requested changes

2022-09-05 10:41 UTC, cachedout approved these changes
Good change 👍

2022-09-05 11:46 UTC, amannocci approved these changes

2022-09-05 11:47 UTC, merged