ci(action): add scorecard automation
elastic/apm-pipeline-library pull request #2418
Opened 2023-10-30 19:56 UTC by v1v

As explained in https://github.com/ossf/scorecard-action#installation

## What does this PR do?

Use scorecard to run some analysis for this project

## Why is it important?

Help to see how well the integration works

2023-10-30 20:53 UTC, v1v commented on .github/workflows/scorecard.yml
> +# This workflow uses actions that are not certified by GitHub. They are provided
```suggestion
---
# This workflow uses actions that are not certified by GitHub. They are provided
```

2023-10-30 20:53 UTC, v1v commented on .github/workflows/scorecard.yml
> +    branches: [ "main" ]
```suggestion
    branches: ["main"]
```

2023-10-30 20:54 UTC, v1v commented on .github/workflows/scorecard.yml
> +      # actions: read
```suggestion
```

2023-10-30 20:56 UTC, v1v commented on .github/workflows/scorecard.yml
> +        uses: ossf/scorecard-action@e38b1902ae4f44df626f11ba0734b14fb91f8f86 # v2.1.2
```suggestion
        uses: ossf/scorecard-action@e38b1902ae4f44df626f11ba0734b14fb91f8f86  # v2.1.2
```

2023-10-30 20:56 UTC, v1v commented on .github/workflows/scorecard.yml
> +        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
```suggestion
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8  # v3.1.0
```

2023-10-30 20:56 UTC, v1v commented on .github/workflows/scorecard.yml
> +          #     of the value entered here.
```suggestion
```

2023-10-30 20:56 UTC, v1v commented on .github/workflows/scorecard.yml
> +        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8 # v3.1.0
```suggestion
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8  # v3.1.0
```

2023-10-30 20:56 UTC, v1v commented on .github/workflows/scorecard.yml
> +        uses: github/codeql-action/upload-sarif@17573ee1cc1b9d061760f3a006fc4aac4f944fd5 # v2.2.4
```suggestion
        uses: github/codeql-action/upload-sarif@17573ee1cc1b9d061760f3a006fc4aac4f944fd5  # v2.2.4
```

2023-10-30 20:56 UTC, v1v commented on .github/workflows/scorecard.yml
> +# policy, and support documentation.
```suggestion
```

2023-10-31 13:04 UTC, amannocci requested changes

2023-10-31 13:04 UTC, amannocci commented on .github/workflows/scorecard.yml
> +        uses: ossf/scorecard-action@e38b1902ae4f44df626f11ba0734b14fb91f8f86  # v2.1.2
```suggestion
        uses: ossf/scorecard-action@0864cf19026789058feabb7e87baa5f140aac736  # v2.3.1
```

2023-10-31 13:04 UTC, amannocci commented on .github/workflows/scorecard.yml
> +        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8  # v3.1.0
```suggestion
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32  # v3.1.3
```

2023-10-31 13:04 UTC, amannocci commented on .github/workflows/scorecard.yml
> +        uses: github/codeql-action/upload-sarif@17573ee1cc1b9d061760f3a006fc4aac4f944fd5  # v2.2.4
```suggestion
        uses: github/codeql-action/upload-sarif@74483a38d39275f33fcff5f35b679b5ca4a26a99  # v2.22.5
```

2023-10-31 13:12 UTC, v1v commented on .github/workflows/scorecard.yml
> +        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8  # v3.1.0
Good finding, somehow the workflow UI automation to create this through the UI is not up-to-date :/

2023-10-31 13:22 UTC, amannocci approved these changes
LGTM

2023-10-31 13:30 UTC, merged